### PR TITLE
Add Essential Features

### PR DESCRIPTION
**Pull request by LEARAX**
I added useful things.

### CODE REVIEW

**Comment by vpzomtrrfrt** [comment]
Aside from the license, I don't see any additions here

**Comment by LEARAX** [comment]
> I don't see any additions here

That's the point.

**Comment by vpzomtrrfrt** [comment]
This PR has a misleading title, and contains a large amount of changes I would rather do myself, if at all

**Comment by LEARAX** [comment]
>"I intensely hate people who point at 'community standards'."
-- Aragnon

**Pull request closed without merging**
